
DROP TABLE IF EXISTS list CASCADE;
CREATE TABLE list (
  id SERIAL PRIMARY KEY NOT NULL,
  task_description VARCHAR(255) NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);

